systemLog:
   destination: file
   path: "/db/log/mongod.log"
   logAppend: true

storage:
   journal:
      enabled: true
   dbPath: "/db/data"
   directoryPerDB: true

net:
   bindIp: 0.0.0.0
   port: 26000
setParameter:
   enableLocalhostAuthBypass: false

replication:
   replSetName: alpha


